### ISSUE TITLE
As a user, I want to download data in CSV format so that I can use the data in other applications.

### ISSUE THREAD

**Issue by RelxOff** [RelxOff/zu-bbbearbeiten-stateless#17]
# Acceptance Criteria

|     Given      |      When         |          Then          |
| :------------: | :---------------: | :--------------------: |
| I am in the "Data" view of the application | I click the "Download CSV" button | The application generates and initiates the CSV download with the current data. |

# Subtasks
- [x] Implement a function to generate CSV data.
- [ ] Create a "Download CSV" button in the user interface.
- [ ] Ensure the CSV download works correctly and contains the right data.

# Further information
Please note that the usability of our application depends on this feature. The more user-friendly and reliable the CSV download is, the better the user experience.
